<h1 align="center"><font color="yellow">Pytorch: Introdução</font></h1>

<font color="yellow">Data Scientist.: PhD.Eddy Giusepe Chirinos Isidro</font>

In [ ]:
%conda install requests,matplotlib --yes

In [6]:
%load_ext watermark 
%watermark -v -p numpy,pandas,matplotlib,requests,torch

Python implementation: CPython
Python version       : 3.9.13
IPython version      : 8.13.2

numpy     : 1.24.3
pandas    : 2.0.1
matplotlib: 3.7.1
requests  : 2.31.0
torch     : 2.0.1



In [1]:
import torch

print(torch.__version__)

2.0.1+cu117


Da mesma maneira que em `NumPy` o objeto principal é o `ndarray`, em `Pytorch` o objeto principal é o `Tensor`.Podemos definir um Tensor de maneira similar a como definimos um `array`, incluso podemos inicializar Tensores a partir de arrays.

In [2]:
# Matriz de zeros, 5 filas y 3 colunas
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# Tensor com valores aleatórios
x = torch.randn(5, 3, 2) # Três dimensões
x

tensor([[[-0.0896,  2.8159],
         [ 1.0890,  1.8803],
         [ 0.9904, -0.0473]],

        [[ 1.2058,  0.5175],
         [ 0.0653, -0.0157],
         [-0.1078,  0.7633]],

        [[ 1.5031,  0.2563],
         [-1.1888, -0.6710],
         [-0.9052,  1.4834]],

        [[ 1.7620, -0.4026],
         [ 0.5731, -1.5712],
         [ 0.1636,  1.3509]],

        [[ 0.1666, -0.1505],
         [ 0.7687,  0.9773],
         [-0.6963,  1.5293]]])

In [4]:
# Tensor a partir da lista 
x = torch.tensor([[1, 2, 3],[4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
import numpy as np

# Tensor a partir de um array numpy

a = np.array([[1, 2, 3],[4, 5, 6]])
x = torch.from_numpy(a)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

<font color="orange">Também podemos fazer operações:</font>

In [6]:
# Definimos dois tensores quaisquer

x = torch.randn(3, 3)
y = torch.randn(3, 3)

In [7]:
x

tensor([[ 0.9316, -1.2201,  1.0941],
        [ 0.5352, -0.1876, -0.5875],
        [ 1.4020, -0.0605,  0.2096]])

In [8]:
y

tensor([[ 0.1461, -0.3990, -0.7864],
        [ 2.2729,  0.1853, -0.1231],
        [ 1.1317,  0.3110,  0.3812]])

In [9]:
x + y

tensor([[ 1.0777e+00, -1.6191e+00,  3.0765e-01],
        [ 2.8081e+00, -2.2980e-03, -7.1056e-01],
        [ 2.5338e+00,  2.5051e-01,  5.9080e-01]])

In [10]:
x - y

tensor([[ 0.7855, -0.8212,  1.8805],
        [-1.7377, -0.3730, -0.4644],
        [ 0.2703, -0.3714, -0.1717]])

In [11]:
# Indexado

# primera fila

x[0]

tensor([ 0.9316, -1.2201,  1.0941])

In [12]:
# Segunda fila
x[1]

tensor([ 0.5352, -0.1876, -0.5875])

In [13]:
# Primeira fila, primeira columna

x[0, 0]

tensor(0.9316)

In [14]:
# Primeira fila

x[0, :]

tensor([ 0.9316, -1.2201,  1.0941])

In [15]:
x

tensor([[ 0.9316, -1.2201,  1.0941],
        [ 0.5352, -0.1876, -0.5875],
        [ 1.4020, -0.0605,  0.2096]])

In [16]:
# Troceado

x[:-1, 1:]

tensor([[-1.2201,  1.0941],
        [-0.1876, -0.5875]])

In [17]:
x.shape

torch.Size([3, 3])

In [18]:
# añadimos una dimensión extra

x.view(1, 3, 3).shape

torch.Size([1, 3, 3])

In [19]:
x

tensor([[ 0.9316, -1.2201,  1.0941],
        [ 0.5352, -0.1876, -0.5875],
        [ 1.4020, -0.0605,  0.2096]])

In [20]:
# Esticamos em uma só dimensão

x.view(9).shape

torch.Size([9])

In [21]:
x

tensor([[ 0.9316, -1.2201,  1.0941],
        [ 0.5352, -0.1876, -0.5875],
        [ 1.4020, -0.0605,  0.2096]])

In [22]:
# Usamos -1 para asignar todos los valores restantes a una dimensión

x.view(-1).shape

torch.Size([9])

Podemos transformar um `Tensor` em um `array` com a função `NumPy`.

In [23]:
x.numpy()

array([[ 0.931627  , -1.22014   ,  1.0940636 ],
       [ 0.5351746 , -0.18764025, -0.58746463],
       [ 1.4020193 , -0.06045388,  0.20957144]], dtype=float32)

# <font color="red">Autograd</font>

A qual nos proporciona a possibilidade de calcular DERIVADAS de maneira automática com respeito a qualquer `Tensor`. Pytorch vai construindo de maneira dinamica um `Grafo computacional`. Já veremos como aplicar, também, `backpropagation` (que é simplesmente a Regra da Cadeia da Derivada) no Grafo.

In [24]:
x = torch.tensor(1., requires_grad=True) # Tem que ser TRUE para poder calcular derivadas delas
y = torch.tensor(2., requires_grad=True)
p = x + y


z = torch.tensor(3., requires_grad=True)
g = p * z

In [25]:
x

tensor(1., requires_grad=True)

O Grafo seria o seguinte:

![](https://www.tutorialspoint.com/python_deep_learning/images/computational_graph_equation2.jpg)

<font color="orange">Se queremos calcular as derivadas de `g` com respeito a `x`, `y` e `z`, é tão fácil como chamar à função `backward`:</font>

In [26]:
g.backward()


In [27]:
x.grad

tensor(3.)

In [28]:
y.grad

tensor(3.)

In [33]:
import torch

# Cria um tensor
x = torch.tensor([2.0], requires_grad=True)

# Realiza uma operação com o tensor
y = x**2

# Realiza o backpropagation
y.backward()

# Imprime o gradiente do tensor x
print(x.grad)


tensor([4.])


In [35]:
x.shape

torch.Size([1])