<h1 align="center"><font color="yellow">Pytorch: Introdução</font></h1>

<font color="yellow">Data Scientist.: PhD.Eddy Giusepe Chirinos Isidro</font>

In [ ]:
%conda install requests,matplotlib --yes

In [1]:
%load_ext watermark 
%watermark -v -p numpy,pandas,matplotlib,requests,torch

Python implementation: CPython
Python version       : 3.9.13
IPython version      : 8.13.2

numpy     : 1.24.3
pandas    : 2.0.1
matplotlib: 3.7.1
requests  : 2.31.0
torch     : 2.0.1



In [2]:
import torch

print(torch.__version__)

2.0.1+cu117


Da mesma maneira que em `NumPy` o objeto principal é o `ndarray`, em `Pytorch` o objeto principal é o `Tensor`.Podemos definir um Tensor de maneira similar a como definimos um `array`, incluso podemos inicializar Tensores a partir de arrays.

In [3]:
# Matriz de zeros, 5 filas y 3 colunas
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# Tensor com valores aleatórios
x = torch.randn(5, 3, 2) # Três dimensões
x

tensor([[[-0.7374,  1.7135],
         [-0.4696, -0.1164],
         [-0.3889,  0.6590]],

        [[-0.2802, -0.4591],
         [-0.4477,  0.4694],
         [-1.6343, -1.3672]],

        [[-0.2413,  0.3306],
         [ 1.6258,  0.7844],
         [ 0.2969,  1.0722]],

        [[-2.3716, -0.1056],
         [ 1.2951,  0.2952],
         [-0.8429, -1.8930]],

        [[ 0.5074,  1.0010],
         [-0.6724, -1.2600],
         [ 0.5966, -1.0164]]])

In [5]:
# Tensor a partir da lista 
x = torch.tensor([[1, 2, 3],[4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
import numpy as np

# Tensor a partir de um array numpy

a = np.array([[1, 2, 3],[4, 5, 6]])
x = torch.from_numpy(a)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

<font color="orange">Também podemos fazer operações:</font>

In [7]:
# Definimos dois tensores quaisquer

x = torch.randn(3, 3)
y = torch.randn(3, 3)

In [8]:
x

tensor([[-0.3762, -0.7704,  1.6005],
        [-2.0636, -0.6546,  0.5749],
        [ 0.6602,  0.1619, -0.6536]])

In [9]:
y

tensor([[ 1.0195,  0.0500, -1.6557],
        [ 0.4694,  1.2684, -0.5902],
        [ 1.6305, -0.6576, -0.2525]])

In [10]:
x + y

tensor([[ 0.6433, -0.7204, -0.0552],
        [-1.5942,  0.6139, -0.0153],
        [ 2.2907, -0.4957, -0.9061]])

In [11]:
x - y

tensor([[-1.3957, -0.8204,  3.2562],
        [-2.5330, -1.9230,  1.1652],
        [-0.9702,  0.8195, -0.4012]])

In [12]:
# Indexado

# primera fila

x[0]

tensor([-0.3762, -0.7704,  1.6005])

In [13]:
# Segunda fila
x[1]

tensor([-2.0636, -0.6546,  0.5749])

In [14]:
# Primeira fila, primeira columna

x[0, 0]

tensor(-0.3762)

In [15]:
# Primeira fila

x[0, :]

tensor([-0.3762, -0.7704,  1.6005])

In [16]:
x

tensor([[-0.3762, -0.7704,  1.6005],
        [-2.0636, -0.6546,  0.5749],
        [ 0.6602,  0.1619, -0.6536]])

In [17]:
# Troceado

x[:-1, 1:]

tensor([[-0.7704,  1.6005],
        [-0.6546,  0.5749]])

In [18]:
x.shape

torch.Size([3, 3])

In [19]:
# añadimos una dimensión extra

x.view(1, 3, 3).shape

torch.Size([1, 3, 3])

In [20]:
x

tensor([[-0.3762, -0.7704,  1.6005],
        [-2.0636, -0.6546,  0.5749],
        [ 0.6602,  0.1619, -0.6536]])

In [21]:
# Esticamos em uma só dimensão

x.view(9).shape

torch.Size([9])

In [22]:
x

tensor([[-0.3762, -0.7704,  1.6005],
        [-2.0636, -0.6546,  0.5749],
        [ 0.6602,  0.1619, -0.6536]])

In [23]:
# Usamos -1 para asignar todos los valores restantes a una dimensión

x.view(-1).shape

torch.Size([9])

Podemos transformar um `Tensor` em um `array` com a função `NumPy`.

In [24]:
x.numpy()

array([[-0.37624374, -0.77039766,  1.6005113 ],
       [-2.063632  , -0.65456283,  0.5749298 ],
       [ 0.6602192 ,  0.1618965 , -0.6536258 ]], dtype=float32)

# <font color="red">Autograd</font>

A qual nos proporciona a possibilidade de calcular DERIVADAS de maneira automática com respeito a qualquer `Tensor`. Pytorch vai construindo de maneira dinamica um `Grafo computacional`. Já veremos como aplicar, também, `backpropagation` (que é simplesmente a Regra da Cadeia da Derivada) no Grafo.

In [39]:
x = torch.tensor(1., requires_grad=True) # Tem que ser TRUE para poder calcular derivadas delas
y = torch.tensor(2., requires_grad=True)
p = x + y


z = torch.tensor(3., requires_grad=True)
g = p * z

In [40]:
x

tensor(1., requires_grad=True)

O Grafo seria o seguinte:

![](https://www.tutorialspoint.com/python_deep_learning/images/computational_graph_equation2.jpg)

<font color="orange">Se queremos calcular as derivadas de `g` com respeito a `x`, `y` e `z`, é tão fácil como chamar à função `backward`:</font>

In [41]:
g.backward()


In [42]:
g

tensor(9., grad_fn=<MulBackward0>)

In [43]:
x.grad

tensor(3.)

In [44]:
y.grad

tensor(3.)

In [77]:
import torch

# Cria um tensor
x = torch.tensor([2.0], requires_grad=True)

# Realiza uma operação com o tensor
y = x**2

# Realiza o backpropagation
y.backward()

# Imprime o gradiente do tensor x (Pelo que Eu entendi: Obtemos o valor da Derivada de `y` em relação a `x`, que é 4.0, um tensor.)
print(x.grad)


tensor([4.])
